# Generated by Django 4.1 on 2022-09-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemWishlist',
            new_name='WishlistItem',
        ),
    ]
