# Generated by Django 4.1 on 2022-09-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_itemwishlist_wishlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='ItemWishlist',
        ),
    ]
